/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        tertiary: "#65afff",
        "secondary-fixed": "#e7c5ff",
        "surface-container-high": "#201f21",
        "surface-dim": "#0e0e0f",
        "primary-fixed-dim": "#00deec",
        "surface-variant": "#262627",
        "surface-container-lowest": "#000000",
        "tertiary-fixed": "#72b5ff",
        "on-primary-container": "#005359",
        error: "#ff716c",
        "primary-fixed": "#00eefc",
        "on-secondary-container": "#fff5ff",
        background: "#0e0e0f",
        "surface-tint": "#8ff5ff",
        "on-secondary-fixed-variant": "#7900c6",
        "primary-dim": "#00deec",
        "on-surface-variant": "#adaaab",
        "surface-container": "#1a191b",
        "on-tertiary-container": "#00213e",
        "on-tertiary-fixed": "#001930",
        "tertiary-fixed-dim": "#51a7fe",
        "error-container": "#9f0519",
        "tertiary-dim": "#4aa2f9",
        "on-tertiary-fixed-variant": "#003b68",
        "surface-container-highest": "#262627",
        "secondary-fixed-dim": "#ddb3ff",
        "inverse-primary": "#006a71",
        "inverse-surface": "#fcf8f9",
        "secondary-dim": "#a533ff",
        "on-tertiary": "#002e52",
        "primary-container": "#00eefc",
        "on-primary": "#005d63",
        "on-error-container": "#ffa8a3",
        primary: "#8ff5ff",
        "surface-bright": "#2c2c2d",
        "tertiary-container": "#4aa2f9",
        "on-primary-fixed-variant": "#005e64",
        "on-surface": "#ffffff",
        "secondary-container": "#8c00e5",
        "on-background": "#ffffff",
        "outline-variant": "#484849",
        "on-secondary-fixed": "#500086",
        secondary: "#c47fff",
        "on-error": "#490006",
        outline: "#767576",
        "on-secondary": "#340059",
        "surface-container-low": "#131314",
        "on-primary-fixed": "#003f43",
        "inverse-on-surface": "#565556",
        "error-dim": "#d7383b",
        surface: "#0e0e0f",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Space Grotesk", "sans-serif"],
      },
    },
  },
  plugins: [],
};
