/**
 * Warrant Agent Wallet Generator
 * ================================
 *
 * Creates 4 fresh agent wallets (Owner, Scout, Executor, Treasury) and
 * writes them to an out-file that can be piped into .env or stored in
 * a password manager. Each wallet is a simple secp256k1 key pair — no
 * HD path, no mnemonic persisted to disk.
 *
 * Usage:
 *   pnpm tsx scripts/generate-agent-wallets.ts
 *   pnpm tsx scripts/generate-agent-wallets.ts --out .wallets.json
 *   pnpm tsx scripts/generate-agent-wallets.ts --env
 *
 * The `--env` flag emits `.env`-ready variable lines to stdout instead of
 * JSON. That makes it easy to pipe into `.env.mainnet` / `.env.testnet`.
 *
 * Security:
 *   - Private keys are written with 0600 permissions when using --out.
 *   - The script prints a hard warning: treat output like a hot wallet key.
 *   - You should still fund the Owner wallet only — Scout/Executor/Treasury
 *     need only enough OKB for their expected tx volume.
 */

import { writeFile, chmod } from "node:fs/promises";
import path from "node:path";
import process from "node:process";
import { Wallet } from "ethers";

type GeneratedWallet = {
  role: "owner" | "scout" | "executor" | "treasury";
  label: string;
  address: string;
  privateKey: string;
};

const WALLET_PLAN: Array<{ role: GeneratedWallet["role"]; label: string }> = [
  { role: "owner", label: "Owner / Deployer" },
  { role: "scout", label: "Scout Agent" },
  { role: "executor", label: "Executor Agent" },
  { role: "treasury", label: "Treasury Agent" },
];

function parseArgs(argv: string[]) {
  const args: { out?: string; env?: boolean } = {};
  for (let i = 0; i < argv.length; i += 1) {
    const token = argv[i];
    if (token === "--out" && argv[i + 1]) {
      args.out = argv[i + 1];
      i += 1;
      continue;
    }
    if (token === "--env") {
      args.env = true;
    }
  }
  return args;
}

function toEnvDump(wallets: GeneratedWallet[]) {
  const owner = wallets.find((w) => w.role === "owner")!;
  const scout = wallets.find((w) => w.role === "scout")!;
  const executor = wallets.find((w) => w.role === "executor")!;
  const treasury = wallets.find((w) => w.role === "treasury")!;
  return [
    "# Warrant agent wallets — fill into .env",
    "# Generated by scripts/generate-agent-wallets.ts",
    "# KEEP THESE PRIVATE KEYS SECRET. Only the deployer key is required by",
    "# the deploy script; the agent keys are consumed by the agent runtimes",
    "# later, out-of-band.",
    "",
    `DEPLOYER_PRIVATE_KEY=${owner.privateKey}`,
    `OWNER_WALLET_ADDRESS=${owner.address}`,
    "",
    `SCOUT_AGENT_ADDRESS=${scout.address}`,
    `SCOUT_AGENT_PRIVATE_KEY=${scout.privateKey}`,
    `ATTESTATION_SIGNER_ADDRESS=${scout.address}`,
    "",
    `EXECUTOR_ADDRESS=${executor.address}`,
    `EXECUTOR_AGENT_PRIVATE_KEY=${executor.privateKey}`,
    "",
    `TREASURY_AGENT_ADDRESS=${treasury.address}`,
    `TREASURY_AGENT_PRIVATE_KEY=${treasury.privateKey}`,
    "",
  ].join("\n");
}

async function main() {
  const args = parseArgs(process.argv.slice(2));

  const wallets: GeneratedWallet[] = WALLET_PLAN.map(({ role, label }) => {
    const wallet = Wallet.createRandom();
    return {
      role,
      label,
      address: wallet.address,
      privateKey: wallet.privateKey,
    };
  });

  if (args.env) {
    // Stdout dump, safe to pipe into a file via shell redirection.
    process.stdout.write(toEnvDump(wallets));
    return;
  }

  if (args.out) {
    const outPath = path.resolve(args.out);
    const body = JSON.stringify(
      {
        generatedAt: new Date().toISOString(),
        warning:
          "TREAT THESE PRIVATE KEYS LIKE A HOT WALLET KEY. Do not commit this file. Add it to .gitignore.",
        wallets,
      },
      null,
      2,
    );
    await writeFile(outPath, `${body}\n`, "utf8");
    await chmod(outPath, 0o600);
    console.log(`Wrote ${wallets.length} wallets to ${outPath} (chmod 0600).`);
    return;
  }

  // Default: print a human-readable table + env dump to stdout.
  console.log("\nGenerated Warrant agent wallets:\n");
  for (const w of wallets) {
    console.log(`  ${w.label.padEnd(20)} ${w.address}`);
  }
  console.log("\nPrivate keys (KEEP THESE SECRET — use --out to save to a 0600 file):\n");
  for (const w of wallets) {
    console.log(`  ${w.role.padEnd(10)} ${w.privateKey}`);
  }
  console.log("\n--- .env dump ---");
  console.log(toEnvDump(wallets));
}

main().catch((error: unknown) => {
  const message = error instanceof Error ? error.stack ?? error.message : String(error);
  console.error(message);
  process.exitCode = 1;
});
